---
name: Terraform Plan

env:
  # Terraform environment variables
  TF_CLI_ARGS_init: "-get=true -upgrade=true -input=false -no-color"
  TF_CLI_ARGS_plan: "-input=false -no-color"
  TF_CLI_ARGS_apply: "-input=false -no-color"
  TF_IN_AUTOMATION: true

on:
  workflow_call:
    inputs:
      terraform_version:
        required: false
        type: string
        default: latest
      environment:
        required: false
        type: string
        default: development
      post_comment:
        required: false
        type: boolean
        default: false
      save_plan:
        required: false
        type: boolean
        default: false
    outputs:
      terraform_plan:
        description: Terraform Plan
        value: ${{ jobs.plan.outputs.terraform_plan }}

jobs:
  terraform-plan:
    name: Terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      terraform_plan: ${{ steps.plan.outputs.stdout }}
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color out terraform.tfplan"
        continue-on-error: true

      - name: Save terraform.tfplan
        if: ${{ inputs.save_plan == true }}
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ inputs.environment }}
          path: terraform.tfplan

      - uses: actions/github-script@v5
        if: ${{ inputs.post_comment == true }}
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `
            \`\`\`\n
              ${process.env.PLAN}
            \`\`\`
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
